#!/bin/bash
HOME=$(pwd) 
#echo $HOME >/tmp/home.out 2>&1


#navigate to asadmin
cd ..
HOME=$(pwd)
#echo $HOME
source $HOME/asadmin/src/test/resources/config/config.properties

echo $ASADMIN

$ASADMIN --port 5048 delete-custom-resource testResource2
$ASADMIN --port 5048 delete-instance danInstance1
$ASADMIN --port 5048 delete-cluster danCluster1
	
#
$ASADMIN --port 5048 delete-node-config dummyTestNode1 



