#!/bin/bash
HOME=$(pwd)
#echo $HOME
#echo ""

#navigate to asadmin
cd ../../../../..
HOME=$(pwd)
#echo $HOME
source $HOME/asadmin/src/test/resources/config/config.properties

#source /home/user/gitRepo/payaratests/asadmin/src/test/resources/config/config.properties
echo $ASADMIN

$ASADMIN delete-custom-resource testResource2
$ASADMIN delete-instance danInstance1
$ASADMIN delete-cluster danCluster1
$ASADMIN delete-node-config dummyTestNode1
